# Роадмапы всех направлений: topic_id, title, grade, requires, description.
# Теорию (theory) и задачи дописывают генераторы контента.
import json
T = lambda i, t, g, r, d: {"topic_id": i, "title": t, "grade": g, "requires": r, "description": d}
ROADMAP = {
"common": [
 T("c-terminal","Терминал и Linux для разработчика","intern",[],"Навигация по файлам, права, пайпы, grep, переменные окружения — всё, что нужно разработчику в консоли каждый день."),
 T("c-git-basics","Git: коммиты и история","intern",["c-terminal"],"init, clone, status, add, commit, log, diff, .gitignore и хорошие сообщения коммитов."),
 T("c-http","HTTP: запросы и ответы","intern",["c-terminal"],"Методы, коды статусов, заголовки, тело запроса, JSON, curl и вкладка Network."),
 T("c-debugging","Дебаг: как искать ошибки","intern",[],"Читать трейсбек, воспроизводить баг, сужать поиск, логи и точки останова."),
 T("c-docs","Документация и вопросы коллегам","intern",["c-debugging"],"Как искать ответ, читать официальную документацию и задавать вопрос так, чтобы на него ответили."),
 T("c-git-branches","Git: ветки, merge и pull request","junior",["c-git-basics"],"Ветки, merge, fast-forward, pull request, git flow в команде."),
 T("c-git-conflicts","Git: конфликты, rebase и откат","junior",["c-git-branches"],"Разрешение конфликтов, rebase и interactive rebase, revert, reset, cherry-pick, stash."),
 T("c-networks","Основы сетей: DNS, порты, TCP","junior",["c-http"],"IP, порты, DNS, TCP и UDP, TLS/HTTPS, localhost и что происходит при вводе адреса в браузер."),
 T("c-estimation","Оценка задач и уточняющие вопросы","junior",["c-docs"],"Декомпозиция, стори-поинты, риски, неизвестные и вопросы менеджеру до начала работы."),
 T("c-code-review","Код-ревью: как давать и принимать","junior_plus",["c-git-branches","c-estimation"],"Что смотреть на ревью, как писать комментарии, размер PR, как отвечать на замечания."),
],
"backend": [
 T("be-py-basics","Python: переменные, ввод и вывод","junior",["c-terminal"],"print, input, переменные, числа и строки, преобразование типов, f-строки."),
 T("be-py-control","Python: условия и циклы","junior",["be-py-basics"],"if/elif/else, логические операторы, while, for, range, break и continue."),
 T("be-py-collections","Python: списки, словари, множества","junior",["be-py-control"],"list, dict, set, tuple, методы коллекций, срезы, генераторы списков, сортировка по ключу."),
 T("be-py-functions","Python: функции","junior",["be-py-collections"],"Параметры и значения по умолчанию, *args/**kwargs, возврат значений, области видимости, lambda, чистые функции."),
 T("be-py-oop","Python: ООП","junior",["be-py-functions"],"Классы, объекты, __init__, методы, наследование, инкапсуляция, магические методы, композиция."),
 T("be-py-exceptions","Python: исключения","junior",["be-py-functions"],"try/except/else/finally, raise, свои исключения, когда ловить и когда пробрасывать."),
 T("be-unit-tests","Unit-тесты (pytest)","junior",["be-py-exceptions"],"assert, pytest, фикстуры, параметризация, моки, что и как тестировать."),
 T("be-rest-crud","REST и CRUD","junior",["c-http","be-py-functions"],"Ресурсы, методы, коды ответов, CRUD-операции, идемпотентность GET/PUT/DELETE."),
 T("be-fastapi","Фреймворк FastAPI","junior",["be-rest-crud","be-py-oop"],"Роуты, path/query параметры, тело запроса, модели ответа, зависимости, автодокументация."),
 T("be-sql-basics","SQL: основы","junior",["be-py-collections"],"SELECT, WHERE, ORDER BY, LIMIT, INSERT, UPDATE, DELETE, NULL, типы данных."),
 T("be-orm","ORM: модели и запросы","junior",["be-sql-basics","be-py-oop"],"SQLAlchemy/Django ORM: модели, сессии, фильтры, связи, миграции."),
 T("be-sql-joins","SQL: JOIN и GROUP BY","junior_plus",["be-sql-basics"],"INNER/LEFT JOIN, GROUP BY, HAVING, агрегаты, подзапросы."),
 T("be-validation","Валидация данных","junior_plus",["be-fastapi"],"Pydantic-модели, валидаторы, ограничения полей, понятные ошибки валидации."),
 T("be-api-errors","Обработка ошибок в API","junior_plus",["be-validation","be-py-exceptions"],"Коды 4xx/5xx, единый формат ошибок, обработчики исключений, не отдавать трейсбек клиенту."),
 T("be-auth","Аутентификация: сессии и JWT","junior_plus",["be-api-errors"],"Хеширование паролей, сессии и куки, JWT, access/refresh токены, авторизация по ролям."),
 T("be-docker-local","Docker для локального запуска","junior_plus",["c-terminal","be-fastapi"],"Dockerfile для Python-сервиса, docker compose с базой, переменные окружения, тома."),
 T("be-api-design","Проектирование API","middle",["be-api-errors"],"Пагинация (offset и cursor), версионирование, идемпотентность POST, фильтрация, коды ответов."),
 T("be-indexes","Индексы и EXPLAIN","middle",["be-sql-joins"],"B-tree индексы, составные индексы и порядок колонок, EXPLAIN ANALYZE, когда индекс мешает."),
 T("be-transactions","Транзакции и уровни изоляции","middle",["be-sql-joins","be-orm"],"ACID, уровни изоляции, аномалии, блокировки, SELECT FOR UPDATE, оптимистичные блокировки."),
 T("be-n-plus-one","Проблема N+1","middle",["be-orm","be-sql-joins"],"Как появляется N+1, joinedload/selectinload, select_related/prefetch_related, как заметить в логах."),
 T("be-caching","Кэширование и Redis","middle",["be-indexes","be-api-design"],"Cache-aside, TTL, инвалидация, прогрев, cache stampede, что кэшировать нельзя."),
 T("be-queues","Очереди: Celery, RabbitMQ, Kafka","middle",["be-api-design"],"Фоновые задачи, ретраи, идемпотентные обработчики, at-least-once, партиции Kafka."),
 T("be-async","Асинхронность в Python","middle",["be-fastapi"],"asyncio, async/await, блокирующие вызовы в async-коде, gather, таймауты."),
 T("be-security","Безопасность бэкенда","middle",["be-auth","be-sql-joins"],"SQL-инъекции, секреты в коде, OWASP Top 10, rate limiting, IDOR."),
 T("be-observability","Логи и метрики","middle",["be-api-errors"],"Структурные логи, уровни логирования, correlation id, метрики RED, алерты."),
 T("be-integration-tests","Интеграционные тесты","middle",["be-unit-tests","be-docker-local"],"Тесты с настоящей базой, тестовый клиент API, фикстуры данных, изоляция тестов."),
],
"frontend": [
 T("fe-html","HTML: семантика и формы","junior",["c-http"],"Семантические теги, формы и поля, атрибуты, валидация форм браузером."),
 T("fe-css-basics","CSS: селекторы, каскад, блочная модель","junior",["fe-html"],"Селекторы и специфичность, каскад, box model, box-sizing, единицы измерения."),
 T("fe-css-layout","Flexbox, Grid и адаптивность","junior",["fe-css-basics"],"Flexbox, Grid, медиазапросы, mobile-first, адаптивные картинки."),
 T("fe-js-basics","JavaScript: основы","junior",["c-debugging"],"Типы, let/const, сравнение, функции, массивы и их методы, объекты, деструктуризация."),
 T("fe-js-closures-this","Замыкания и this","junior",["fe-js-basics"],"Области видимости, замыкания, this в разных вызовах, стрелочные функции, bind."),
 T("fe-js-async","Промисы и async/await","junior",["fe-js-closures-this"],"Promise, then/catch, async/await, Promise.all, обработка ошибок в асинхронном коде."),
 T("fe-dom","DOM и события","junior",["fe-html","fe-js-basics"],"querySelector, изменение DOM, события, всплытие, делегирование, preventDefault."),
 T("fe-react-basics","Основы React","junior",["fe-dom","fe-js-closures-this"],"JSX, компоненты, рендер списков и key, условный рендер, useState."),
 T("fe-react-components","Компоненты, пропсы и состояние","junior_plus",["fe-react-basics"],"Пропсы, подъём состояния, контролируемые формы, useEffect и его зависимости, композиция."),
 T("fe-api-loading","Работа с API: загрузка и ошибки","junior_plus",["fe-js-async","fe-react-components"],"fetch, состояния загрузки/ошибки/пусто, отмена запросов, гонки ответов."),
 T("fe-typescript","TypeScript: основы","junior_plus",["fe-js-basics"],"Типы, интерфейсы, union, типизация функций и пропсов, strict-режим."),
 T("fe-vite","Сборка через Vite","junior_plus",["fe-typescript","fe-react-basics"],"Dev-сервер, переменные окружения, сборка, алиасы, прокси к API."),
 T("fe-ts-advanced","Продвинутый TypeScript","middle",["fe-typescript"],"Дженерики, утилитарные типы, сужение типов, discriminated unions, типизация API-ответов."),
 T("fe-state","Управление состоянием","middle",["fe-api-loading"],"Локальное и глобальное состояние, контекст, стор (Zustand/Redux), серверное состояние (TanStack Query)."),
 T("fe-performance","Производительность фронтенда","middle",["fe-state","fe-vite"],"Лишние ререндеры, memo/useMemo/useCallback, lazy loading, размер бандла, Web Vitals."),
 T("fe-event-loop","Event loop и рендеринг","middle",["fe-js-async"],"Стек вызовов, макро- и микрозадачи, requestAnimationFrame, долгие задачи и лаги интерфейса."),
 T("fe-cors","CORS","middle",["fe-api-loading","c-http"],"Same-origin policy, preflight, заголовки CORS, куки и credentials, прокси в разработке."),
 T("fe-ssr","SSR и SSG","middle",["fe-performance"],"CSR, SSR, SSG, гидратация, ошибки гидратации, когда что выбирать."),
 T("fe-testing","Тесты на фронтенде","middle",["fe-react-components"],"Vitest, Testing Library, моки fetch, e2e на Playwright, что тестировать."),
 T("fe-a11y","Доступность (a11y)","middle",["fe-html","fe-react-components"],"Семантика, alt, label, фокус и клавиатура, ARIA, контраст."),
 T("fe-security","XSS и хранение токенов","middle",["fe-cors"],"XSS и dangerouslySetInnerHTML, CSP, где хранить токены, httpOnly-куки, CSRF."),
],
"devops": [
 T("do-linux-processes","Linux: процессы и сигналы","junior",["c-terminal"],"ps, top, kill и сигналы, фоновые процессы, память и CPU, OOM killer."),
 T("do-linux-perms","Linux: пользователи и права","junior",["c-terminal"],"Пользователи и группы, chmod/chown, sudo, права на ключи и сокеты."),
 T("do-systemd-logs","systemd и журналы","junior",["do-linux-processes"],"Юниты systemd, systemctl, перезапуск, journalctl, logrotate."),
 T("do-networks","Сети для DevOps","junior",["c-networks"],"TCP/IP, порты, ss/netstat, DNS и dig, файрвол, диагностика «не открывается»."),
 T("do-bash","Bash-скрипты","junior",["do-linux-perms"],"Переменные, условия, циклы, set -euo pipefail, коды выхода, кавычки."),
 T("do-dockerfile","Dockerfile","junior",["do-bash"],"Инструкции, слои и кэш, multi-stage сборка, непривилегированный пользователь, .dockerignore."),
 T("do-compose","docker-compose","junior_plus",["do-dockerfile","do-networks"],"Сервисы, сети, тома, depends_on и healthcheck, переменные окружения."),
 T("do-ci","CI/CD: GitHub Actions и GitLab CI","junior_plus",["do-compose","c-git-branches"],"Пайплайны, стадии, кэш, артефакты, секреты CI, деплой по тегу."),
 T("do-nginx","Nginx как reverse proxy","junior_plus",["do-networks","do-systemd-logs"],"server и location, proxy_pass, заголовки, TLS, статика, 502/504."),
 T("do-cloud","Базовое облако","junior_plus",["do-networks"],"Виртуальные машины, сети и security groups, объектное хранилище, IAM, стоимость."),
 T("do-k8s-basics","Kubernetes: Deployment и Service","middle",["do-compose","do-cloud"],"Pod, Deployment, ReplicaSet, Service, probes, requests/limits, ConfigMap."),
 T("do-k8s-ingress-helm","Kubernetes: Ingress и Helm","middle",["do-k8s-basics","do-nginx"],"Ingress, TLS, Helm-чарты, values, релизы и откаты."),
 T("do-k8s-debug","Kubernetes: дебаг подов","middle",["do-k8s-basics"],"CrashLoopBackOff, ImagePullBackOff, OOMKilled, Pending, kubectl describe/logs/exec, events."),
 T("do-terraform","Terraform","middle",["do-cloud"],"Провайдеры, ресурсы, state и его блокировка, plan/apply, модули, переменные."),
 T("do-ansible","Ansible","middle",["do-bash","do-systemd-logs"],"Инвентори, плейбуки, модули, идемпотентность, handlers, роли."),
 T("do-monitoring","Мониторинг: Prometheus и Grafana","middle",["do-k8s-basics"],"Метрики, PromQL, RED/USE, SLO, алерты без шума."),
 T("do-logging","Логи: Loki и ELK","middle",["do-monitoring"],"Сбор логов, структурные логи, LogQL, ретеншн, поиск по trace id."),
 T("do-deploy-strategies","Стратегии деплоя","middle",["do-k8s-ingress-helm","do-ci"],"Rolling, blue-green, canary, фиче-флаги, откат, миграции БД при деплое."),
 T("do-secrets","Секреты и Vault","middle",["do-k8s-basics","do-ci"],"Где хранить секреты, Kubernetes Secrets, Vault, ротация, утечки в git."),
 T("do-backups","Бэкапы и восстановление","middle",["do-cloud"],"Стратегии бэкапов, RPO/RTO, pg_dump и PITR, проверка восстановления."),
 T("do-incidents","Инциденты и постмортемы","middle",["do-monitoring","do-logging"],"Роли на инциденте, смягчение vs исправление, коммуникация, blameless-постмортем."),
],
"fullstack": [
 T("fs-contract","Контракт API между фронтом и бэком","middle",["be-api-design","fe-ts-advanced"],"OpenAPI, генерация типов, обратная совместимость, версии контракта."),
 T("fs-auth-e2e","Авторизация через весь стек","middle",["be-auth","fe-security","do-secrets"],"Логин от формы до базы: куки vs токены, refresh, CSRF, выход со всех устройств."),
 T("fs-feature-e2e","Фича целиком: от тикета до прода","middle",["be-orm","fe-api-loading","do-ci"],"Декомпозиция фичи на бэк, фронт и инфраструктуру, миграции, фиче-флаг, выкладка."),
 T("fs-realtime","Реалтайм: WebSocket и SSE","middle",["be-async","fe-event-loop","do-nginx"],"Polling, SSE, WebSocket, проксирование через Nginx, масштабирование соединений."),
 T("fs-performance-e2e","Производительность всего стека","middle",["be-caching","fe-performance","do-monitoring"],"Где тормозит: фронт, сеть, API или база — и как это доказать метриками."),
 T("fs-release","Релиз без простоя","middle",["do-deploy-strategies","be-transactions"],"Обратно совместимые миграции (expand/contract), порядок выкладки фронта и бэка, откат."),
 T("fs-incident-e2e","Инцидент через весь стек","middle",["do-incidents","fe-cors","be-observability"],"Разбор инцидентов, где причина прячется на стыке фронта, бэка и инфраструктуры."),
 T("fs-system-design","Системный дизайн: итоговое ревью","middle",["fs-contract","fs-auth-e2e","fs-feature-e2e","fs-realtime","fs-performance-e2e","fs-release","fs-incident-e2e"],"Проектирование сервиса целиком: требования, нагрузка, хранилища, кэш, очереди, отказоустойчивость."),
],
}
if __name__ == "__main__":
    json.dump(ROADMAP, open("Tools/Content/spec/roadmap.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
    print({k: len(v) for k, v in ROADMAP.items()}, sum(len(v) for v in ROADMAP.values()))
